// admin/admin.js - ZEROHUB Automated Admin Panel Engine
import { authService, dbService } from '../firebase.js';

// Почтаи электронии ягонаи ТУ барои амният
const ADMIN_EMAIL = "azizzodavalijon2010@gmail.com";

// 1. САНҶИШИ АМНИЯТӢ (Худкор)
authService.onAuthStateCheck((user) => {
    if (!user || user.email !== ADMIN_EMAIL) {
        // Агар админ ворид нашуда бошад ё почта бегона бошад, худкор ба саҳифаи login мебарорад
        window.location.href = 'login.html';
    } else {
        // Агар ҳамааш дуруст бошад, омори зиндаро ба кор меандозад
        startLiveAnalytics();
    }
});

// Тугмаи Баромад (Logout)
const logoutBtn = document.getElementById('logoutBtn');
if (logoutBtn) {
    logoutBtn.addEventListener('click', async () => {
        await authService.logout();
        window.location.href = 'login.html';
    });
}

// 2. ОМОРИ ЗИНДА (Realtime Analytics)
function startLiveAnalytics() {
    dbService.listenToStats((stats) => {
        document.getElementById('statTotalProducts').innerText = stats.totalProducts;
        document.getElementById('statTotalViews').innerText = stats.totalViews;
        document.getElementById('statTotalDownloads').innerText = stats.totalDownloads;
    });
}

// 3. ИЛОВА КАРДАНИ МАҲСУЛОТ БО ТАВЛИДИ ХУДКОРИ ID ВА САНА
const addForm = document.getElementById('addProductForm');
if (addForm) {
    addForm.addEventListener('submit', async (e) => {
        e.preventDefault();

        // Гирифтани ҳамаи маҳсулот барои ҳисоб кардани ID-и навбатӣ
        const allProducts = await dbService.getAllProducts();
        const nextNumber = allProducts.length + 1;
        
        // Худкор сохтани ID бо формати касбӣ: ZH-000001
        const autoGeneratedId = "ZH-" + String(nextNumber).padStart(6, '0');

        // Сплит кардани скриншотҳо (аз вергул ҷудо кардан)
        const screenshotsRaw = document.getElementById('prodScreenshots').value;
        const screenshotsArray = screenshotsRaw ? screenshotsRaw.split(',').map(url => url.trim()) : [];

        // Ҷамъоварии объект тибқи архитектураи омодаи база
        const newProductData = {
            id: autoGeneratedId, // ID-и худкор
            title_ru: document.getElementById('prodTitleRu').value.trim(),
            title_en: document.getElementById('prodTitleEn').value.trim(),
            type: document.getElementById('prodType').value,
            category: document.getElementById('prodCategory').value.trim().toLowerCase(),
            version: document.getElementById('prodVersion').value.trim(),
            size: document.getElementById('prodSize').value.trim(),
            downloadUrl: document.getElementById('prodDownloadUrl').value.trim(),
            isFeatured: document.getElementById('prodIsFeatured').checked,
            media: {
                icon: document.getElementById('prodIconUrl').value.trim(),
                trailer: document.getElementById('prodTrailerUrl').value.trim() || null,
                screenshots: screenshotsArray
            },
            description_ru: document.getElementById('prodDescRu').value.trim(),
            description_en: document.getElementById('prodDescEn').value.trim(),
            stats: {
                views: 0,
                downloads: 0
            }
        };

        try {
            // Фиристодан ба Firebase
            await dbService.createProduct(newProductData);
            
            alert(`Муваффақият! Маҳсулот бо ID-и худкори ${autoGeneratedId} илова шуд!`);
            addForm.reset(); // Тоза кардани форма пас аз муваффақият
        } catch (error) {
            alert("Хатогӣ ҳангоми илова кардан: " + error.message);
        }
    });
}
